apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - Infra/*
build:
  local:
    push: false
  artifacts:
    - image: ajfer/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: "."
    - image: ajfer/express
      context: server
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: "."
