services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}